# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/AXI_DMA/AXI_DMA.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_DMA || ORIG_REF_NAME==AXI_DMA} -quiet] -quiet

# IP: bd/AXI_DMA/ip/AXI_DMA_axi_dma_0_0/AXI_DMA_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_DMA_axi_dma_0_0 || ORIG_REF_NAME==AXI_DMA_axi_dma_0_0} -quiet] -quiet

# IP: bd/AXI_DMA/ip/AXI_DMA_processing_system7_0_0/AXI_DMA_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_DMA_processing_system7_0_0 || ORIG_REF_NAME==AXI_DMA_processing_system7_0_0} -quiet] -quiet

# IP: bd/AXI_DMA/ip/AXI_DMA_auto_pc_0/AXI_DMA_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_DMA_auto_pc_0 || ORIG_REF_NAME==AXI_DMA_auto_pc_0} -quiet] -quiet

# IP: bd/AXI_DMA/ip/AXI_DMA_ps7_0_axi_periph_0/AXI_DMA_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_DMA_ps7_0_axi_periph_0 || ORIG_REF_NAME==AXI_DMA_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AXI_DMA/ip/AXI_DMA_rst_ps7_0_50M_0/AXI_DMA_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_DMA_rst_ps7_0_50M_0 || ORIG_REF_NAME==AXI_DMA_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/AXI_DMA/ip/AXI_DMA_xbar_0/AXI_DMA_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_DMA_xbar_0 || ORIG_REF_NAME==AXI_DMA_xbar_0} -quiet] -quiet

# IP: bd/AXI_DMA/ip/AXI_DMA_auto_us_0/AXI_DMA_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_DMA_auto_us_0 || ORIG_REF_NAME==AXI_DMA_auto_us_0} -quiet] -quiet

# IP: bd/AXI_DMA/ip/AXI_DMA_auto_us_1/AXI_DMA_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_DMA_auto_us_1 || ORIG_REF_NAME==AXI_DMA_auto_us_1} -quiet] -quiet

# IP: bd/AXI_DMA/ip/AXI_DMA_auto_us_2/AXI_DMA_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_DMA_auto_us_2 || ORIG_REF_NAME==AXI_DMA_auto_us_2} -quiet] -quiet

# IP: bd/AXI_DMA/ip/AXI_DMA_auto_pc_1/AXI_DMA_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_DMA_auto_pc_1 || ORIG_REF_NAME==AXI_DMA_auto_pc_1} -quiet] -quiet

# IP: bd/AXI_DMA/ip/AXI_DMA_axi_mem_intercon_0/AXI_DMA_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_DMA_axi_mem_intercon_0 || ORIG_REF_NAME==AXI_DMA_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/AXI_DMA/ip/AXI_DMA_axis_data_fifo_0_0/AXI_DMA_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_DMA_axis_data_fifo_0_0 || ORIG_REF_NAME==AXI_DMA_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/AXI_DMA/ip/AXI_DMA_xlconcat_0_0/AXI_DMA_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_DMA_xlconcat_0_0 || ORIG_REF_NAME==AXI_DMA_xlconcat_0_0} -quiet] -quiet

# XDC: /home/subi/codes/FPGA_projects/AXI-DMA/AXI-DMA.gen/sources_1/bd/AXI_DMA/AXI_DMA_ooc.xdc
