# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/subi/codes/FPGA_projects/AXI-DMA/AXI-DMA.srcs/sources_1/bd/AXI_DMA/ip/AXI_DMA_processing_system7_0_0/AXI_DMA_processing_system7_0_0.xci
# IP: The module: 'AXI_DMA_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/subi/codes/FPGA_projects/AXI-DMA/AXI-DMA.gen/sources_1/bd/AXI_DMA/ip/AXI_DMA_processing_system7_0_0/AXI_DMA_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_DMA_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/subi/codes/FPGA_projects/AXI-DMA/AXI-DMA.srcs/sources_1/bd/AXI_DMA/ip/AXI_DMA_processing_system7_0_0/AXI_DMA_processing_system7_0_0.xci
# IP: The module: 'AXI_DMA_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/subi/codes/FPGA_projects/AXI-DMA/AXI-DMA.gen/sources_1/bd/AXI_DMA/ip/AXI_DMA_processing_system7_0_0/AXI_DMA_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_DMA_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
